### ISSUE TITLE
Any release plans?

### ISSUE THREAD

**Issue by seanson** [KevinGeLe/SmartSRT#1]
Hi!

This looks like an awesome project and I'd love to see something using the new NeMo tech for SRT generation. Any plans on releasing the scripts used any time soon?

**Comment by KevinGeLe** [comment]
Yes, I already have made most of the code independent of each other. Now I just need to make it all work seamlessly together and of course make some parameters for you guys, I'm currently trying out faster-whisper and seeing if that could be viable. Shouldn't take more than a month at most.
